# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vincent Hounshell
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hounvs.github.io" # the base hostname & protocol for your site
twitter_username: hounvs
github_username:  hounvs
youtube_username: hounvs
twitch_username:  hounvs_Vince

# Build settings
markdown: kramdown
exclude: ['.vs', 'exclude']

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"